
// app/layout.js

// Import a Font 
import { Inter, Rubik } from "next/font/google";

// Stylesheets
import "./globals.css";

// components
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });    // Get a subset from the font

export const metadata = {                       // Metadata for the entire app
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {      // Children (default param) are all sub pages. Render the Navbar before rendering all child components
  return (
    <html lang="en">
      <body className={rubik.className}>
        <nav>
          <Navbar />                                   
        </nav>
        {children}  
      </body>
    </html>
  );
}
